### ISSUE TITLE
BLUE Leds "prevent" you from sleeping

### ISSUE THREAD

**Issue by chrisrock1984** [dshiffman/dodowDIY#1]
As you might know, blue leds are counterproductive when you want to sleep ;-)
Just a remark, not an issue.

BR

**Comment by dshiffman** [comment]
Thanks Chris, this is a copy of the Dodow (https://www.mydodow.com/) and they claim in their FAQ that _"The color blue was chosen after much testing, based on the generally accepted perception that blue is calming. Blue light in high doses can help wake you up by inhibiting melatonin secretion, but Dodow does not. Being projected on the ceiling, the light signal, at its maximum intensity and for someone who is lying in bed, has a very low intensity"_ . The faint glow on the ceiling fading in and out and gradually slowing down is actually quite soothing in my experience.  I think the general statement about blue light is true for brighter sources not faint glows.
